version: '3'
services:
  web_server:
    build: server
    hostname: web
    container_name: web
  zalenium:
    image: "dosel/zalenium"
    container_name: zalenium
    hostname: zalenium
    tty: true
    volumes:
      - zal_videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    command: >
      start --desiredContainers 2
            --maxDockerSeleniumContainers 4
            --screenWidth 1920 --screenHeight 1080
            --videoRecordingEnabled true
            --retentionPeriod 3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/grid/console"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: unless-stopped
    labels:
      autoheal: "true"
  selenium-test:
    build: selenium-test
    depends_on:
      - zalenium
      - web_server
  autoheal:
    container_name: autoheal
    image: "willfarrell/autoheal"
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes: 
  zal_videos: